# -*- coding: utf-8 -*-
"""string_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19JlMntAZWoibQPELH1EV14yPnKdC7iUP
"""

'''
1. Write a file string_utils.py with functions:
  - to_uppercase(text)
  - to_lowercase(text)
  - word_count(text)
'''

def to_uppercase(text):
  return text.upper()

def to_lowercase(text):
  return text.lower()

def word_count(text):
  return len(text.split())